# Generated by Django 4.1.7 on 2023-04-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingpaymentrequest',
            name='approve_at',
        ),
        migrations.RemoveField(
            model_name='prepaymentrequest',
            name='approve_at',
        ),
    ]
