# Generated by Django 4.1.7 on 2023-04-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_chargingpaymentrequest_approve_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingpaymentrequest',
            name='order_name',
            field=models.CharField(default='차량충전대금', max_length=100, verbose_name='결제내역'),
        ),
        migrations.AlterField(
            model_name='prepaymentrequest',
            name='order_name',
            field=models.CharField(default='선불금충전대금', max_length=100, verbose_name='결제내역'),
        ),
    ]
